// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Nonsense = require("./Nonsense.bs.js");
var ReactDom = require("react-dom");

console.log("Hello World1");

var nonsense = document.querySelector("#nonsense");

if (nonsense == null) {
  console.log("we could not find nonsense div!");
} else {
  ReactDom.render(React.createElement(Nonsense.make, { }), nonsense);
}

/*  Not a pure module */
